services:
    ntvy95.hide.listener:
        class: ntvy95\hide\event\listener
        arguments:
            - @user
            - @template
            - @dbal.conn
        tags:
            - { name: event.listener }
